# Generated by Django 4.1.6 on 2023-02-20 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='food',
            new_name='food_name',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='year',
        ),
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 20)),
        ),
    ]
