# Generated by Django 4.1.6 on 2023-02-28 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_rename_food_meal_food_name_remove_meal_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 28)),
        ),
        migrations.AlterField(
            model_name='meal',
            name='location',
            field=models.CharField(help_text='Enter the place you buy the food.', max_length=50),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Midnight Snack', 'Midnight Snack')], default='Breakfast', max_length=20),
        ),
    ]
