# Generated by Django 4.1.6 on 2023-02-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_alter_meal_date_alter_meal_location_alter_meal_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='food_name',
            field=models.CharField(max_length=60),
        ),
    ]
