# Generated by Django 4.1.6 on 2023-03-02 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_alter_meal_food_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=60)),
                ('calorie', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 2)),
        ),
    ]
