# Generated by Django 4.1.7 on 2023-03-28 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_caloriechart_alter_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calorie',
            field=models.IntegerField(help_text='The unit is kcal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 28)),
        ),
    ]
